#!/usr/bin/env python3
"""
generate-roadmap.py — generate docs/roadmap.md, grouping backlog items by milestone.

Reads docs/backlog.md through lib/backlog.py (single parsing source) and produces an overview page
next to the GitHub milestones: one section per milestone (open/done counts and a table of items)
plus an "Unplanned" section for open items without one.

The page is GENERATED and COMMITTED: the `generated-pages` gate in CI regenerates it with --check
and fails if it diverged. Do not edit it by hand.

Usage:
  python3 docs/scripts/generate-roadmap.py            # writes docs/roadmap.md
  python3 docs/scripts/generate-roadmap.py --check    # exit 1 if the output differs from the file
Requires: stdlib only.
"""
import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "lib"))
import backlog as B   # noqa: E402

OUT = os.path.normpath(os.path.join(HERE, "..", "roadmap.md"))
PRIO_ORDER = {"high": 0, "medium": 1, "low": 2, "": 3}
STATUS_GLYPH = {"done": "done", "open": "open"}


def _md_escape(s):
    return s.replace("|", "\\|")


def _sort_key(it):
    # open before done; then priority (high→low); then id
    return (it["status"].lower() == "done", PRIO_ORDER.get(it["priority"].lower(), 3), it["id"])


def render(items):
    planned = [it for it in items if it["milestone"]]
    milestones = sorted({it["milestone"] for it in planned})

    L = []
    L.append("# Roadmap — backlog milestones")
    L.append("")
    L.append("<!-- GENERATED by docs/scripts/generate-roadmap.py — do NOT edit by hand. -->")
    L.append("> **Generated** page: [`docs/scripts/generate-roadmap.py`](scripts/generate-roadmap.py) "
             "reads [`docs/backlog.md`](backlog.md) (the single source). It sits next to the "
             "[GitHub milestones](https://github.com/Allan-Nava/Docker-FFmpeg-Nvenc/milestones), "
             "which the sync creates and fills.")
    L.append("")
    tot_open = sum(1 for it in planned if it["status"].lower() != "done")
    tot_done = sum(1 for it in planned if it["status"].lower() == "done")
    L.append(f"_{len(milestones)} milestones · {len(planned)} planned items "
             f"({tot_open} open · {tot_done} done)._")
    L.append("")

    for ms in milestones:
        its = sorted((it for it in planned if it["milestone"] == ms), key=_sort_key)
        n_open = sum(1 for it in its if it["status"].lower() != "done")
        n_done = sum(1 for it in its if it["status"].lower() == "done")
        L.append(f"## {ms}")
        L.append("")
        L.append(f"_{n_open} open · {n_done} done_")
        L.append("")
        L.append("| id | Title | Priority | Status |")
        L.append("|----|--------|----------|--------|")
        for it in its:
            st = STATUS_GLYPH.get(it["status"].lower(), it["status"])
            prio = it["priority"] or "—"
            L.append(f"| `{it['id']}` | {_md_escape(it['title'])} | {prio} | {st} |")
        L.append("")

    # unplanned: open only (done items without a milestone are history, they live in the backlog)
    unplanned = sorted((it for it in items if not it["milestone"]
                        and it["status"].lower() != "done"), key=_sort_key)
    L.append("## Unplanned (no milestone)")
    L.append("")
    L.append(f"_{len(unplanned)} open items without a milestone. Assign one with "
             "`- **milestone**: <title>` in [`backlog.md`](backlog.md)._")
    L.append("")
    if unplanned:
        L.append("| id | Title | Priority |")
        L.append("|----|--------|----------|")
        for it in unplanned:
            prio = it["priority"] or "—"
            L.append(f"| `{it['id']}` | {_md_escape(it['title'])} | {prio} |")
        L.append("")

    return "\n".join(L).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description="Generate docs/roadmap.md from the backlog milestones.")
    ap.add_argument("--backlog", default=os.path.join(HERE, "..", "backlog.md"))
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--check", action="store_true",
                    help="writes nothing: exit 1 if the output differs from the existing file (for CI)")
    args = ap.parse_args()

    items = B.parse_backlog(os.path.normpath(args.backlog))
    content = render(items)

    if args.check:
        existing = ""
        if os.path.isfile(args.out):
            existing = open(args.out, encoding="utf-8").read()
        if existing != content:
            print("roadmap.md is stale: re-run `python3 docs/scripts/generate-roadmap.py`")
            return 1
        print("roadmap.md is up to date.")
        return 0

    open(args.out, "w", encoding="utf-8").write(content)
    n_ms = len({it["milestone"] for it in items if it["milestone"]})
    print(f"wrote {os.path.relpath(args.out)} · {n_ms} milestones.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
